title: "You Are Not Your Stack"
description: "A book about untangling your identity from your technology choices."
theme: minima
url: "https://cloudstreet-dev.github.io"
baseurl: "/You-Are-Not-Your-Stack"

header_pages: []

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .github

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
